/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as AppRouteImport } from './app/routes/_app'
import { Route as AppIndexRouteImport } from './app/routes/_app/index'
import { Route as AppCoursesRouteImport } from './app/routes/_app/courses'
import { Route as AppEmployeesRouteImport } from './app/routes/_app/employees'
import { Route as AppOrganisationRouteImport } from './app/routes/_app/organisation'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/courses': typeof AppCoursesRoute
  '/employees': typeof AppEmployeesRoute
  '/organisation': typeof AppOrganisationRoute
}
export interface FileRoutesByTo {
  '/courses': typeof AppCoursesRoute
  '/employees': typeof AppEmployeesRoute
  '/organisation': typeof AppOrganisationRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/courses': typeof AppCoursesRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/organisation': typeof AppOrganisationRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses' | '/employees' | '/organisation'
  fileRoutesByTo: FileRoutesByTo
  to: '/courses' | '/employees' | '/organisation' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/courses'
    | '/_app/employees'
    | '/_app/organisation'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisation': {
      id: '/_app/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoursesRoute: typeof AppCoursesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoursesRoute: AppCoursesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
