packages:
  - apps/*
  - shared/*
allowBuilds:
  '@parcel/watcher': false
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.40'
  - '@tanstack/react-start-client@1.168.38'
  - '@tanstack/react-start-rsc@0.1.58'
  - '@tanstack/react-start-server@1.167.45'
  - '@tanstack/react-start@1.168.59'
  - '@tanstack/router-core@1.171.33'
  - '@tanstack/router-generator@1.167.39'
  - '@tanstack/router-plugin@1.168.41'
  - '@tanstack/start-client-core@1.170.33'
  - '@tanstack/start-plugin-core@1.171.48'
  - '@tanstack/start-server-core@1.169.38'
  - '@tanstack/start-storage-context@1.167.35'
